In [1]:
#  NumPy is a lineat algebra library for Python, the reason it is so important
#  for Data Science with Python is that almost all of the libraries in the PyData
#  Ecosystem rely on NumPy as one of their main building blocks.

#  Numpy is also incredibly fast, as it has bindings to C libraries

In [3]:
# pip install numpy

In [4]:
# Numpy arrays are the main way we will use Numpy throughout the course.
# Numpy arrays essentially come in two flavors: vectors and matrices.
# Vectors are strictly 1-d arrays and matrices are 2-d(but you should note a matrix can still have only one row or one column)

In [5]:
my_list =[1,2,3]

In [6]:
my_list

[1, 2, 3]

In [7]:
import numpy as np

In [10]:
arr = np.array(my_list)

In [12]:
arr #One Dimensional Array

array([1, 2, 3])

In [13]:
my_mat =[[1,2,3],[4,5,6],[7,8,9]]

In [15]:
arr2 = np.array(my_mat)

In [16]:
arr2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [20]:
np.arange(0,11,2) 

#first argument is used for start number
#second argument is used for last number
#third argument is used for step size

array([ 0,  2,  4,  6,  8, 10])

In [21]:
np.zeros(3)

array([0., 0., 0.])

In [22]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [23]:
 np.zeros((2,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [24]:
np.ones(4)

array([1., 1., 1., 1.])

In [27]:
np.ones((7,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [30]:
 np.linspace(0,5,10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [32]:
np.linspace(0,5,100)
#third argument specifies number of points we want from first argument to the second argument

array([0.        , 0.05050505, 0.1010101 , 0.15151515, 0.2020202 ,
       0.25252525, 0.3030303 , 0.35353535, 0.4040404 , 0.45454545,
       0.50505051, 0.55555556, 0.60606061, 0.65656566, 0.70707071,
       0.75757576, 0.80808081, 0.85858586, 0.90909091, 0.95959596,
       1.01010101, 1.06060606, 1.11111111, 1.16161616, 1.21212121,
       1.26262626, 1.31313131, 1.36363636, 1.41414141, 1.46464646,
       1.51515152, 1.56565657, 1.61616162, 1.66666667, 1.71717172,
       1.76767677, 1.81818182, 1.86868687, 1.91919192, 1.96969697,
       2.02020202, 2.07070707, 2.12121212, 2.17171717, 2.22222222,
       2.27272727, 2.32323232, 2.37373737, 2.42424242, 2.47474747,
       2.52525253, 2.57575758, 2.62626263, 2.67676768, 2.72727273,
       2.77777778, 2.82828283, 2.87878788, 2.92929293, 2.97979798,
       3.03030303, 3.08080808, 3.13131313, 3.18181818, 3.23232323,
       3.28282828, 3.33333333, 3.38383838, 3.43434343, 3.48484848,
       3.53535354, 3.58585859, 3.63636364, 3.68686869, 3.73737

In [35]:
np.eye(4) #number of rows = no of columns = 4
          #Square matrix

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [36]:
np.random.rand(5,5)

array([[0.04281048, 0.16793227, 0.87057427, 0.34376731, 0.2791276 ],
       [0.0358743 , 0.95810738, 0.33434935, 0.80623634, 0.25509947],
       [0.74150735, 0.19322469, 0.59900037, 0.88903094, 0.82837173],
       [0.34594998, 0.39133739, 0.40943027, 0.51245176, 0.35042615],
       [0.90140341, 0.7319983 , 0.41160303, 0.05396452, 0.45922263]])

In [37]:
np.random.rand(5)

array([0.35531993, 0.7291135 , 0.2042364 , 0.71699757, 0.07525236])

In [39]:
np.random.randn(2)

array([-0.36241014,  1.16336013])

In [40]:
np.random.randn(4,4)

array([[-0.42754845, -0.19841627,  2.02085825,  1.77324178],
       [-1.33547192, -0.65734009, -0.10997823,  1.2213496 ],
       [-1.06823627,  0.04834405, -0.24686149,  0.38204955],
       [ 0.44785512, -0.03095025,  1.63906088, -0.83601819]])

In [45]:
np.random.randint(1,100,10)

array([22, 86, 57, 30, 93,  5, 12, 54, 94, 40])

In [46]:
np.random.randint(1,100,3)

array([62, 33, 84])

In [47]:
arr = np.arange(25)

In [48]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [66]:
ranarr = np.random.randint(0,50,10)

In [67]:
ranarr

array([27, 14, 40, 45,  1, 37,  4,  5, 41, 31])

In [68]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [69]:
ranarr

array([27, 14, 40, 45,  1, 37,  4,  5, 41, 31])

In [70]:
ranarr.max()

45

In [71]:
ranarr.min()

1

In [72]:
ranarr.argmax()

3

In [73]:
ranarr.argmin()

4

In [75]:
arr1 = arr.reshape(5,5)

In [76]:
arr1

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [77]:
arr1.dtype

dtype('int32')

In [78]:
from numpy.random import randint

In [79]:
randint(2,10)

5